apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: us-west-1

vpc: # DNS hostname and DNS resolution must be enabled
  subnets:
    private: # NatGW must be active to allow priv sub to reach the internet
      us-west-1a: { id: subnet-0c7d7402f1c671f45 }
      us-west-1b: { id: subnet-0d5f02f4ff10e6c36 }
   

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true